version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: integrate-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - integrate
  integrate:
    build:
      args:
         user: integrate
         uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: integrate
    container_name: integrate
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php:/usr/local/etc/php
    networks:
      - integrate
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    container_name: integrate-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: integrate
      MYSQL_USER: integrate
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: admin.root
    ports:
      - 33068:3306
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - integrate
networks:
    integrate:
